# Generated by Django 3.0.8 on 2020-07-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='名稱')),
                ('ingredients', models.CharField(max_length=400, verbose_name='食材')),
                ('picture', models.FileField(upload_to='', verbose_name='圖片')),
                ('difficulty', models.CharField(choices=[('Easy', '容易'), ('Medium', '中等'), ('Hard', '困難')], max_length=10, verbose_name='製作指南')),
            ],
            options={
                'verbose_name': '食譜',
                'verbose_name_plural': '食譜',
            },
        ),
    ]
