# Generated by Django 3.0.8 on 2020-07-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='prep_guide',
            field=models.TextField(default='hello this is default cookbooks', verbose_name='製作指南'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveIntegerField(default='20', verbose_name='準備時間'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('Easy', '容易'), ('Medium', '中等'), ('Hard', '困難')], max_length=10, verbose_name='製作難度'),
        ),
    ]
